"""Deterministic semantic IR to native KiCad schematic compilation."""

from __future__ import annotations

import hashlib
import json
import os
import re
import tempfile
import uuid
from dataclasses import dataclass
from pathlib import Path

from kicad_sch_api import Schematic
from kicad_sch_api.core.pin_utils import get_component_pin_info

from pcbdraft import __version__
from pcbdraft.core.errors import PCBDraftError, ValidationError
from pcbdraft.domain.ir import Design
from pcbdraft.domain.parts import PartGraph, PartRecord
from pcbdraft.domain.scope import assert_supported

KICAD_NAMESPACE = uuid.UUID("68ff00d5-68cd-53c0-a336-f25343c70161")


@dataclass(frozen=True)
class SchematicGeneration:
    path: Path
    sha256: str
    root_uuid: str
    component_uuids: dict[str, str]
    label_count: int
    no_connect_count: int

    def to_dict(self) -> dict[str, object]:
        return {
            "path": str(self.path),
            "sha256": self.sha256,
            "root_uuid": self.root_uuid,
            "component_uuids": dict(sorted(self.component_uuids.items())),
            "label_count": self.label_count,
            "no_connect_count": self.no_connect_count,
        }


def stable_kicad_uuid(design_id: str, kind: str, identifier: str) -> str:
    """Return a version-stable UUID for one generated KiCad object."""
    return str(uuid.uuid5(KICAD_NAMESPACE, f"{design_id}/{kind}/{identifier}"))


def inspect_native_schematic(path: str | Path) -> dict[str, object]:
    """Return a bounded semantic snapshot of a native KiCad schematic."""
    source = Path(path)
    if source.suffix != ".kicad_sch" or source.is_symlink():
        raise ValidationError("schematic inspection requires a non-symlink .kicad_sch")
    try:
        resolved = source.resolve(strict=True)
        if resolved.stat().st_size > 128 * 1024 * 1024:
            raise ValidationError("schematic exceeds the inspection size limit")
        schematic = Schematic.load(resolved)
    except ValidationError:
        raise
    except Exception as exc:
        raise PCBDraftError(f"KiCad schematic inspection failed: {exc}") from exc
    fields = ("Manufacturer", "MPN", "Part_ID", "Lifecycle", "Trust")
    components = []
    for component in schematic.components:
        properties = {}
        for name in fields:
            raw = component.properties.get(name)
            if isinstance(raw, dict) and isinstance(raw.get("value"), str):
                properties[name] = raw["value"]
        components.append(
            {
                "reference": component.reference,
                "value": component.value,
                "symbol": component.lib_id,
                "footprint": component.footprint,
                "uuid": component.uuid,
                "position_mm": [
                    round(float(component.position.x), 6),
                    round(float(component.position.y), 6),
                ],
                "rotation_deg": round(float(component.rotation) % 360, 6),
                "properties": dict(sorted(properties.items())),
            }
        )
    labels = sorted(
        {
            str(label.text)
            for label in schematic.labels
            if isinstance(label.text, str) and label.text
        }
    )
    return {
        "schema": "pcbdraft-schematic-snapshot",
        "version": 1,
        "root_uuid": schematic.uuid,
        "components": sorted(components, key=lambda item: item["reference"]),
        "label_names": labels,
        "label_count": len(list(schematic.labels)),
        "no_connect_count": len(list(schematic.no_connects)),
    }


def generate_schematic(
    design: Design,
    output: str | Path,
    *,
    graph: PartGraph | None = None,
) -> SchematicGeneration:
    """Compile a validated IR into a self-contained modern ``.kicad_sch`` file."""
    resolved_graph = graph or PartGraph.bundled()
    assert_supported(design)
    resolved_graph.assert_design(
        design,
        check_libraries=True,
        allow_provisional=design.metadata.get("assurance") == "provisional",
    )
    target = Path(output).resolve(strict=False)
    if target.suffix != ".kicad_sch":
        raise ValidationError("schematic output must end in .kicad_sch")
    target.parent.mkdir(parents=True, exist_ok=True)
    if target.is_symlink():
        raise ValidationError("refusing to replace a schematic symlink")

    root_uuid = stable_kicad_uuid(design.design_id, "schematic", "root")
    schematic = Schematic.create(
        name=target.stem,
        generator="pcbdraft",
        generator_version=__version__,
        uuid=root_uuid,
    )
    # The pinned backend exposes no public title-block setter.
    schematic._data["title_block"] = {
        "title": design.name,
        "rev": design.revision,
        "company": "Generated by PCBDraft",
        "comment1": f"Semantic IR: {design.content_hash()}",
        "comment2": "Generated output; review the circuit and layout before fabrication",
    }
    component_uuids: dict[str, str] = {}
    wrappers: dict[str, object] = {}
    try:
        for component in sorted(design.components, key=lambda entry: entry.reference):
            part = resolved_graph.get(component.part_id)
            component_uuid = stable_kicad_uuid(
                design.design_id, "component", component.id
            )
            component_uuids[component.id] = component_uuid
            x_mm, y_mm = _schematic_position(component)
            wrapper = schematic.components.add(
                part.symbol,
                reference=component.reference,
                value=component.value,
                position=(x_mm, y_mm),
                footprint=part.footprint,
                rotation=0,
                component_uuid=component_uuid,
                grid_units=False,
            )
            wrapper.add_properties(
                {
                    "Manufacturer": part.manufacturer,
                    "MPN": part.mpn,
                    "Part_ID": part.id,
                    "Lifecycle": str(part.lifecycle.get("status", "unknown")),
                    "Trust": part.trust,
                    "Datasheet": _datasheet(part),
                    "Description": part.description,
                },
                hidden=True,
            )
            if not hasattr(wrapper, "pin_uuids"):
                raise ValidationError(
                    f"multi-unit symbols are not supported by this compiler: {part.symbol}"
                )
            for pin in part.pins:
                if wrapper.get_pin(pin.number) is None:
                    raise ValidationError(
                        f"symbol {part.symbol} has no contracted pin {pin.number}"
                    )
                wrapper.pin_uuids[pin.number] = stable_kicad_uuid(
                    design.design_id,
                    "symbol_pin",
                    f"{component.id}/{pin.number}",
                )
            wrappers[component.id] = wrapper

        connected: set[tuple[str, str]] = set()
        label_count = 0
        for net in sorted(design.nets, key=lambda entry: entry.id):
            for endpoint in sorted(net.endpoints):
                component = next(
                    entry
                    for entry in design.components
                    if entry.id == endpoint.component
                )
                label_uuid = stable_kicad_uuid(
                    design.design_id,
                    "net_label",
                    f"{net.id}/{endpoint.component}/{endpoint.pin}",
                )
                schematic.add_label(
                    net.name,
                    pin=(component.reference, endpoint.pin),
                    uuid=label_uuid,
                )
                connected.add((endpoint.component, endpoint.pin))
                label_count += 1

        no_connect_count = 0
        for component in sorted(design.components, key=lambda entry: entry.reference):
            wrapper = wrappers[component.id]
            part = resolved_graph.get(component.part_id)
            for pin in part.pins:
                if (component.id, pin.number) in connected:
                    continue
                pin_info = get_component_pin_info(wrapper, pin.number)
                if pin_info is None:
                    raise ValidationError(
                        f"cannot locate {component.reference} pin {pin.number}"
                    )
                schematic.no_connects.add(
                    pin_info[0],
                    no_connect_uuid=stable_kicad_uuid(
                        design.design_id,
                        "no_connect",
                        f"{component.id}/{pin.number}",
                    ),
                )
                no_connect_count += 1

        temporary_fd, temporary_name = tempfile.mkstemp(
            prefix=f".{target.name}.", suffix=".tmp", dir=target.parent
        )
        os.close(temporary_fd)
        temporary = Path(temporary_name)
        try:
            schematic.save(temporary, preserve_format=False)
            _repair_malformed_private_library_properties(temporary)
            os.chmod(temporary, 0o644)
            os.replace(temporary, target)
        finally:
            temporary.unlink(missing_ok=True)
    except ValidationError:
        raise
    except Exception as exc:
        raise PCBDraftError(f"KiCad schematic generation failed: {exc}") from exc

    digest = hashlib.sha256(target.read_bytes()).hexdigest()
    return SchematicGeneration(
        path=target,
        sha256=digest,
        root_uuid=root_uuid,
        component_uuids=component_uuids,
        label_count=label_count,
        no_connect_count=no_connect_count,
    )


def _repair_malformed_private_library_properties(path: Path) -> None:
    """Work around kicad-sch-api 0.5.6's KiCad 10 private-property bug.

    KiCad symbol libraries may contain ``(property private ...)`` KLC annotation
    records. The pinned backend shifts those fields when embedding a symbol and
    emits invalid schematic syntax beginning ``(property "private" ...)``. These
    annotations have no electrical or visual meaning, but preserving them avoids
    KiCad's library-symbol mismatch warning. Repair only the shifted first line
    while preserving the rest of each property block.
    """

    lines = path.read_text(encoding="utf-8").splitlines(keepends=True)
    result: list[str] = []
    repaired = 0
    pattern = re.compile(
        r'^(?P<indent>\s*)\(property "private" "(?P<name>(?:\\.|[^"])*)" '
        r"(?P<description>.*?)(?P<newline>\r?\n)?$"
    )
    for line in lines:
        if '(property "private"' not in line:
            result.append(line)
            continue
        match = pattern.fullmatch(line)
        if match is None:
            raise ValidationError(
                "malformed private symbol property has an unsafe layout"
            )
        result.append(
            f"{match.group('indent')}(property private "
            f"{json.dumps(match.group('name'), ensure_ascii=False)} "
            f"{json.dumps(match.group('description'), ensure_ascii=False)}"
            f"{match.group('newline') or ''}"
        )
        repaired += 1
    if repaired:
        path.write_text("".join(result), encoding="utf-8", newline="")


def _schematic_position(component: object) -> tuple[float, float]:
    placement = component.placement
    if placement is None:
        raise ValidationError(f"component {component.id} has no placement seed")
    # Expand physical board coordinates into a readable A4 schematic while retaining
    # semantic grouping.  The library snaps these values to KiCad's 1.27 mm grid.
    return 20 + placement.x_mm * 2.54, 20 + placement.y_mm * 2.54


def _datasheet(part: PartRecord) -> str:
    evidence = next(
        (
            entry.locator
            for entry in part.evidence
            if entry.kind in {"datasheet", "manufacturer_record"}
        ),
        "",
    )
    return evidence
